package com.hockeyhurd.fairexchange.mod.util;

import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

/**
 * Simple class for injecting mod metadata info into mcmod.info file.
 *
 * @author hockeyhurd
 * @version 1/14/2017.
 */
public final class FairExchangeMetadata {

	private boolean result = false;

	public FairExchangeMetadata(FMLPreInitializationEvent event) {
		injectData(event.getModMetadata());
	}

	private void injectData(final ModMetadata metadata) {
		metadata.autogenerated = false;

		if (!metadata.authorList.isEmpty()) metadata.authorList.set(0, "hockeyhurd");
		else metadata.authorList.add("hockeyhurd");

		metadata.credits = "hockeyhurd";
		metadata.modId = Reference.MOD_NAME;
		metadata.version = Reference.VERSION;
		metadata.name = Reference.MOD_NAME;
		metadata.url = "https://goo.gl/OYaAfo";
		metadata.logoFile = "";
		metadata.description = "A simple exchange mod similar to EE3 minium stone.";

		result = true;
	}

	public boolean getResult() {
		return result;
	}

}
